### ISSUE TITLE
v1?

### ISSUE THREAD

**Issue by ortonomy** [microsoftgraph/msgraph-sdk-ruby#217]
### Is your feature request related to a problem? Please describe the problem.

Build an app using the graph SDK

### Describe the solution you'd like.

To publish V1 that covers all graph APIs with all features not currently supported

### Additional context?

-

**Comment by baywet** [comment]
Hi, thank you for using the Microsoft craft SDK and for reaching out. Is your question about missing apis from V1 in the SDK? Or is your question about this SDK reaching a stable version?

**Comment by ortonomy** [comment]
Both! @baywet 

1. I am building an app where the app needs to maintain access to the user's credentials on their behalf to sync mail/calendar for an extended period of time. (similar to these guys - https://www.nylas.com/). However none of the "Authentication providers" seem to support being able to pass an existing credential set (token, refresh token) and then pass that to the graph API SDK. It's borderline unuseable without this feature

2. There are a bunch of things missing as described in readme

3. when will it reach a stable version. Have you given up? If so, I will go build in go instead.

**Comment by baywet** [comment]
1. if you already have an access token because your application already integrates with an authentication infrastructure (e.g. baked in the web application framework you're using), you can simply derive from [the base bearer authentication provider](https://github.com/microsoft/kiota-abstractions-ruby/blob/04f0941f9f60797ea2a21928ce8484aecd598a70/lib/microsoft_kiota_abstractions/authentication/base_bearer_token_authentication_provider.rb#L8) and pass that to the client/request adapter instead.
2. can you be more explicit here? I'm not sure I'm following what's missing
3. Work on Ruby is paused indefinitely. Given the other priorities I don't expect any work to happen this semester.

**Comment by ortonomy** [comment]
> Work on Ruby is paused indefinitely. Given the other priorities I don't expect any work to happen this semester.

That's all that needed to be said. Not sure what semester means, though. Is that some internal Microsoft speak?

**Comment by baywet** [comment]
Haha, probably. I meant from July to December 2024
