### ISSUE TITLE
What is timeline to first production release?

### ISSUE THREAD

**Issue by philCryoport** [microsoftgraph/msgraph-sdk-ruby#35]
Hi there,

We're a bit uncomfortable using a gem that is a "release candidate...still in preview status".  What is the timeline to first production release?

Would you also please publish a version history for the alpha/beta/gamma versions up until now?  There is no version history listed -- other than commit history --  yet there's been development for multiple years by the looks of it...

Thanks!

**Comment by philCryoport** [comment]
Hi @MIchaelMainer / @darrelmiller is there anyone I can contact to plead / beg / lobby to set up a production release timeline?  Or if not, do you at least have a gap analysis somewhere to show exactly what the open-source community would need to pull-request/merge in order to be able to say that this is a production release?

I ask because until there is an official production release, my dev team is instead opting to manually implement their own client based upon the REST documentation -- and as a dev yourself, I'm assuming you understand my preference for a production release from the manufacturer...

**Comment by ethanfann** [comment]
@philCryoport I'd recommend simply using HTTParty with direct calls to the Graph API. I've found figuring out how to do anything beyond enumerating through users and groups to be extremely difficult.

**Comment by darrelmiller** [comment]
Hey @philCryoport , sorry I don't have any good news for you.  Currently the developers that we have are all committed to working on other SDKs.  I think at this point @ethanfann 's advice is wise.  Until we can have some folks dedicated to bringing this inline with our other SDKs, I don't want make commitments to you that I won't be able to keep.

**Comment by doz87** [comment]
By the looks of it, this repo has all but been abandoned.
Especially comparing to the other SDKs that you have which have a lot more recent activity.
This Gem is basically unusable in its current state and doesn't really have any usable functionality.

I think you should state something to that effect in the README so that people get a heads up instead of diving in to find no functionality and having to implement their own library anyway.

I realise that its stated up front to be a "release candidate" and still in preview status, but honestly its very far away from getting to release and should probably be stated for clarity.

**Comment by ethanfann** [comment]
@doz87 I've went ahead and opened a PR to clarify the readme

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
