### ISSUE TITLE
Enterprise consumer needing immediate support

### ISSUE THREAD

**Issue by sudostack** [microsoftgraph/msgraph-sdk-ruby#43]
I haven't gotten a response in your documentation about an issue that I've submitted. I currently work with a team that has an enterprise account with you. Since this SDK isn't being supported, we are rolling one internally. The docs are fairly clear, except the response from your API seems incongruent. Could you please have a look? https://github.com/microsoftgraph/microsoft-graph-docs/issues/4092

You guys have a beta endpoint for notifications as well, but some of the code samples (I've looked at the NodeJS one) include subscription creation to subscribe to notifications. They set up an endpoint to receive notifications. If you know of one that does, it may be helpful in resolving the issue above, but because they do not, it's been a black box for me.

**Comment by darrelmiller** [comment]
The issue you reported, as you suggested, seems to be a service issue and not an SDK issue.  This is even more likely considering as you stated you aren't using our currently unsupported Ruby SDK and you have rolled your own.  For enterprise customers who need to open a support ticket, I recommend logging into the Azure Portal and using the "Help and Support" feature to open a ticket.  That will ensure the issue is triaged and routed appropriately.

![image](https://user-images.githubusercontent.com/447694/54246320-cba3a600-450a-11e9-80a4-c9200e25b040.png)
